apiVersion: v1
kind: Service
metadata:
  name: {{ include "viz-site.fullname" . }}
  labels:
    {{- include "viz-site.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "viz-site.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
